[package]
name = "get_reads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "get_reads"
crate-type = ["dylib"]

[dependencies.cpython]
version = "0.7"
features = ["extension-module"]